main: com.goldfrosch.TwipRoulette
name: TwipRoulette
version: 0.0.1-SNAPSHOT
author: GoldFrosch
api-version: 1.18
depend: [LibsDisguises]
commands:
  game:
    description: HO!
    test:
      buff:
        description: HOU!
      item:
        description: HOU!
      monster:
        description: HOU!
      disaster:
        description: HOU!
    disaster:
      description: HOU!!
    spin:
      description: HOU!
    start:
      description: HOU!