main: com.goldfrosch.TwipRoulette
name: TwipRoulette
version: 0.0.1-SNAPSHOT
author: GoldFrosch
depend: [LibsDisguises]
commands:
  game:
    description: HO!
    test:
      description: HOU!
    disaster:
      description: HOU!!
    spin:
      description: HOU!
    start:
      description: HOU!